### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by madhur** [huytd/swift-http#2]
Here is what I get on my MAC:

```
madhur@Madhurs-MacBook-Pro:~/swift-http (master)
$ swift build
<unknown>:0: error: no such file or directory: 'build'
```

**Comment by huytd** [comment]
Hi @madhur, you're getting that error because the built-in Swift compiler which shipped with Xcode does not contains `Swift Package Manager`. You have to download Swift 2.2 open source version and install it. You can see this link for installation guide https://swift.org/download/#apple-platforms

**Comment by madhur** [comment]
Ok. :+1:
