### ISSUE TITLE
Move to SemanticVersioning convention

### ISSUE THREAD

**Issue by codegefluester** [huytd/swift-http#5]
According to the [documentation](see), Swift packages should follow the [SemanticVersioning](http://semver.org/) convention. Currently, this package is not installable as a dependency as the tag is named v0.1-linux.

I recommend to implement SemanticVersioning so developers will be able to pull it in as a dependency.

**Comment by codegefluester** [comment]
Seems like this was now done with a recent PR

**Comment by huytd** [comment]
:dancers:
